[identities]
cole-h = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINMcTaqUZSwv6YW8lx/JhsAZTdNSSC2fR8Pgk8woeFKh"
scadrial = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILcskrV03RenqOdkvVFP2iPBaAlY3XR8QqWbK5Ckeb4I"
scar = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIB49A+yOs8RgOwDRKOw555IcXDvWy3YtyRR7r9c4Zge"
yolen = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP8S2yfK1ENqpkfEQ8w7ISyOBOV7bGNvQUnhQtMcdbEO"

[groups]
all = [
  "cole-h",
  "scadrial",
  "scar",
  "yolen",
]

[[paths]]
glob = "hosts/scadrial/*"
identities = [
  "cole-h",
  "scadrial",
]

[[paths]]
glob = "hosts/scar/*"
identities = [
  "cole-h",
  "scar",
]

[[paths]]
glob = "hosts/yolen/*"
identities = [
  "cole-h",
  "yolen",
]

[[paths]]
glob = "*"
groups = [
  "all",
]
