keys:
  - &cole-h 68B80D57B2E54AC3EC1F49B0B37E0F2371016A4C
  - &scadrial 9065537245a17fe06fd7450b72e61ee11fcaac29
  - &scar 1b156a1dd5c8bfced0f2dfe04d0089d916427d93
  - &yolen 4b5936652542484dcd6a0c574595eb67a6e1c486

creation_rules:
  - path_regex: hosts/scadrial
    key_groups:
      - pgp:
          - *cole-h
          - *scadrial
  - path_regex: hosts/scar
    key_groups:
      - pgp:
          - *cole-h
          - *scar
  - path_regex: hosts/yolen
    key_groups:
      - pgp:
          - *cole-h
          - *yolen
  - key_groups:
      - pgp:
          - *cole-h
          - *scadrial
          - *scar
